travis:
  secure:
    BINSTAR_TOKEN: UMkZJyLamn0f9NCx2J2k5v8NCLuw7rzF+0UwRefSHdYN93Tqhf3PZ1M4u6ccgDJOQCi8SyzPUOboL7Y5syNu7vj6k/MTKRvHf9PBR2wEL+AmJMgMCjXvqzin2/iq6sCmxPpcntoSOAvuYdBrOkL+2UyyIGB2vYgtaNyfoXh9p8BD6iJuySY51v5gBVoM6aLLJjEMEllbL3EhAZZc21mRDhV5kQRWvrc68kB1bBXMwkBCS57feztGzzRJdAtq5+5zmIikBpX6/IZX3hmW0G6RNSlS4e7+iVV7kRsd8KP5yv70hMLhw2uOs7gAzjkTf8xf9WFQY73czutaE5UfEu+04LW02fJI1LMCpY7J/yZYeeTwtTPtsYh2+h6EzuFR2TN7CPWnV+AEAHsUQvdsiNu58tIuQ3JickrfBNCalkGHnIl5qnAWaSk4f6nrrBqexufb3SbTZhxuMX2vZI2SRFx+YFDtjB3hjkpTNMonuvgnmh756SLFFjj5h0tz9W3ki+2HTzAMVFrD+IUIOgQs4PnqSEAJuN3ZS2uRAdfGb8aoaepDgQyYfy9Xx2vG3p5llDTmBVr60ljFyjeK/P8C4E25MxDbQzngNqkTKyL6uFXvu5DKnE08RrUYW7e6kiHSITNtCZ8TjdqA9KBElgQJ+WUskTEZ9jZGM5UX5l/WtGBbskY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
