travis:
  secure:
    BINSTAR_TOKEN: KJlgJmln1q72GF4N6M0O0QVstEqOUhYxsJMT6ScWzJ+1sZYyntir2dhIV1YOIqmdhuy9jubh58rKcko8F/VRVDQHkmxr/2RSWLkyOXoNDsTNUrcJxl5QfGziUMskfLkD+Uivzf6aAPwZrJROqQA1/BJvaGYbbGKO1LM/lMWb3MsiLius7DT031JsCY4Oh/+S0mxnZoyRyQIq59xJl0KM6PVkd09Xrp0WKexGpccjtQIJL/QaPkgS+cNgK8pKXlDn173kc6/VYvXN+3k/W5YwNRdlbNefIX3Rl8CfbWEOWCYc8jsvHosbToFV7Hw/62TXT+IuxxZIOdh9YSb844tlnM3Va7ZTqFLwktQNbncA3PdJVRJzYAWVCqI1C4jy5s+2JDWu+dF6vGleVy1mi+ho6rGY/um5W4zgE+D5wGt4SjOZ9qMaUW5s+DP88o57URGMCwXexcPmurLEqqR7aWE1u5tOQwPGHEzncd4TkKCMFqZIuCNs0VoGf1zhIbvdFDXuSLJ+x4Zbf3IZmGEqaOqB1v4rJLZpHt2FHjuXhyIetoi2EUlIi35HeGXDZxYvwzslfvN1ioiHKocD6HR5nD1bzeL0WLTBbzYGa+1uKVGhhs5QGmEvs+rYSbCQjCk/P3khyJLOWj1x8xc6V30rRYSNVkBqhChGT3RZQHYyIyazipA=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
